---
- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Crear pagina personaliza
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reiniciar Apache

- name: Iniciar servicio Apache
  service:
    name: apache2
    state: started
    enabled: yes
