---
# tasks file for roles/samba
- name: Instalar Samba
  apt:
    name: samba
    state: present

- name: Crear grupo
  group:
    name: "{{ samba_group }}"
    state: present

- name: Crear usuario sin shell
  user:
    name: "{{ samba_user }}"
    shell: /usr/sbin/nologin
    groups: "{{ samba_group }}"
    append: yes

- name: Crear directorio compartido
  file:
    path: "{{ samba_share_path }}"
    state: directory
    owner: root
    group: "{{ samba_group }}"
    mode: '2770'

- name: Configurar Samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: Reiniciar Samba

- name: Establecer contraseña Samba
  shell: (echo "{{ samba_password }}"; echo "{{ samba_password }}") | smbpasswd -s -a {{ samba_user }}
  no_log: true
